services:
  backend:
    build: .
    image: ozanemrahyakupoglu/may-backend:${VERSION:-1.0.0}
    container_name: may-backend
    ports:
      - "7001:7001"
    environment:
      DB_HOST: 46.225.97.71
      DB_PORT: 7000
      DB_USER: MAY_APP
      DB_PASSWORD: 123456789
